CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS admins (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL DEFAULT '管理员', password_hash TEXT NOT NULL,
 session_version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), last_login TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS categories (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS tags (name TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS guides (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title TEXT NOT NULL, destination TEXT NOT NULL, country TEXT NOT NULL DEFAULT '', summary TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '',
 days INTEGER NOT NULL DEFAULT 1 CHECK(days BETWEEN 1 AND 365), budget TEXT NOT NULL DEFAULT '', season TEXT NOT NULL DEFAULT '',
 tags JSONB NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(tags)='array'), cover TEXT NOT NULL DEFAULT '/static/assets/lake.jpg',
 status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('public','private','draft')),
 sources TEXT NOT NULL DEFAULT '', verified_at TEXT NOT NULL DEFAULT '', sample BOOLEAN NOT NULL DEFAULT false,
 category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
 revision INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
 CHECK(status <> 'public' OR length(trim(body))>0)
);
CREATE INDEX IF NOT EXISTS guides_status ON guides(status,deleted_at);
CREATE INDEX IF NOT EXISTS guides_tags ON guides USING GIN(tags);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS login_attempts (ip TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS login_attempts_ip ON login_attempts(ip,created);
CREATE TABLE IF NOT EXISTS media (
 filename TEXT PRIMARY KEY, name TEXT NOT NULL, bytes BIGINT NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL DEFAULT '',
 details JSONB NOT NULL DEFAULT '{}', ip TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_created ON audit_log(created_at DESC);
INSERT INTO settings(key,value) VALUES
 ('site_name','"行笺"'),('tagline','"收藏旅途的灵感，把每一次出发都安排得刚刚好。"'),
 ('footer','"让每一次出发，都有迹可循。"'),('show_samples','true') ON CONFLICT DO NOTHING;
INSERT INTO schema_migrations(version) VALUES(1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS travel_records (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title TEXT NOT NULL, destination TEXT NOT NULL,
 start_date DATE NOT NULL, end_date DATE,
 summary TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', actual_cost TEXT NOT NULL DEFAULT '',
 photos JSONB NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(photos)='array' AND jsonb_array_length(photos)<=30),
 cover TEXT NOT NULL DEFAULT '/static/assets/lake.jpg',
 guide_id BIGINT REFERENCES guides(id) ON DELETE SET NULL, guide_day INTEGER CHECK(guide_day BETWEEN 1 AND 365),
 status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('public','private','draft')),
 revision INTEGER NOT NULL DEFAULT 1,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
 CHECK(end_date IS NULL OR end_date>=start_date),
 CHECK(status<>'public' OR length(trim(body))>0 OR jsonb_array_length(photos)>0)
);
CREATE INDEX IF NOT EXISTS travel_records_timeline ON travel_records(start_date DESC,id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS travel_records_guide ON travel_records(guide_id);
CREATE INDEX IF NOT EXISTS travel_records_photos ON travel_records USING GIN(photos);
INSERT INTO schema_migrations(version) VALUES(2) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS agent_tasks (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 kind TEXT NOT NULL CHECK(kind IN ('change','diagnose','chat','publish','rollback')),
 prompt TEXT NOT NULL, parent_id BIGINT REFERENCES agent_tasks(id),
 status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','testing','ready','done','failed','cancelled','publishing','published','manual')),
 cancel_requested BOOLEAN NOT NULL DEFAULT false,
 request JSONB NOT NULL DEFAULT '{}', result TEXT NOT NULL DEFAULT '', report JSONB NOT NULL DEFAULT '{}',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS agent_tasks_queue ON agent_tasks(id) WHERE status='queued';
INSERT INTO schema_migrations(version) VALUES(3) ON CONFLICT DO NOTHING;
